# Aula 10 – Seleção e Filtros de Dados

## Objetivo da aula

Nesta aula vamos aprender como selecionar colunas, filtrar linhas e organizar dados no **Pandas**.

Você irá aprender:

- Seleção de colunas
- Uso de **loc** e **iloc**
- Filtros booleanos
- Uso de **query()**
- Uso de **unique()**
- Uso de **value_counts()**
- Uso de **sort_values()**

# 1. Importando o Pandas

Vamos começar importando a biblioteca **Pandas**.

In [1]:
import pandas as pd

# 2. Lendo a base de dados

Vamos carregar a base que será usada nos exemplos.

In [2]:
arquivo = r"C:\Users\Joao.Maria\Documents\curso-python_joao_pedro\Base\Base_analitica_vendas.xlsx"

base_vendas = pd.read_excel(arquivo, sheet_name="Base")

# 3. Seleção de colunas

Podemos selecionar uma ou mais colunas da base.

### Selecionando uma coluna

In [3]:
base_vendas["DESCRICAOCLIENTE"]

0                ATACADO BRINDE & CIA
1                ATACADO BRINDE & CIA
2                ATACADO BRINDE & CIA
3                ATACADO BRINDE & CIA
4                ATACADO BRINDE & CIA
                     ...
43117    DISTRIBUIDORA ATLETA BEBIDAS
43118    DISTRIBUIDORA ATLETA BEBIDAS
43119    DISTRIBUIDORA ATLETA BEBIDAS
43120    DISTRIBUIDORA ATLETA BEBIDAS
43121    DISTRIBUIDORA ATLETA BEBIDAS
Name: DESCRICAOCLIENTE, Length: 43122, dtype: str

### Selecionando várias colunas

In [4]:
base_vendas[["DESCRICAOCLIENTE", "NOMEPRODUTO", "VALORLIQUIDO"]]

,DESCRICAOCLIENTE,NOMEPRODUTO,VALORLIQUIDO
0,ATACADO BRINDE & CIA,Isotônico Uva Vitaminado 500ml,472.41
1,ATACADO BRINDE & CIA,Cerveja Lager Standard 350ml (Lata),1973.87
2,ATACADO BRINDE & CIA,Suco de Laranja Integral 500ml,444.46
3,ATACADO BRINDE & CIA,Néctar de Uva Premium 1L,397.90
4,ATACADO BRINDE & CIA,Lúpulo em Pellet para Brassagem 5kg,1304.07
...,...,...,...
43117,DISTRIBUIDORA ATLETA BEBIDAS,Shot Energético Ultra-Concentrado 60ml,1228.52
43118,DISTRIBUIDORA ATLETA BEBIDAS,Hard Seltzer Limão 310ml,1480.32
43119,DISTRIBUIDORA ATLETA BEBIDAS,Hard Seltzer Amora 310ml,1553.94
43120,DISTRIBUIDORA ATLETA BEBIDAS,Hard Seltzer Tangerina 310ml,1845.10
43121,DISTRIBUIDORA ATLETA BEBIDAS,Hard Seltzer Abacaxi 310ml,88.88

# 4. Seleção com loc

O **loc** seleciona dados usando **rótulos**: nomes de linhas e colunas.

### Selecionando linhas e colunas específicas

In [5]:
base_vendas.loc[0:4, ["DESCRICAOCLIENTE", "NOMEPRODUTO", "VALORLIQUIDO"]]

       DESCRICAOCLIENTE                          NOMEPRODUTO  VALORLIQUIDO
0  ATACADO BRINDE & CIA       Isotônico Uva Vitaminado 500ml        472.41
1  ATACADO BRINDE & CIA  Cerveja Lager Standard 350ml (Lata)       1973.87
2  ATACADO BRINDE & CIA       Suco de Laranja Integral 500ml        444.46
3  ATACADO BRINDE & CIA             Néctar de Uva Premium 1L        397.90
4  ATACADO BRINDE & CIA  Lúpulo em Pellet para Brassagem 5kg       1304.07

### Selecionando todas as linhas de uma coluna

In [6]:
base_vendas.loc[:, ["DESCRICAOCLIENTE", "VALORLIQUIDO"]]

                   DESCRICAOCLIENTE  VALORLIQUIDO
0              ATACADO BRINDE & CIA        472.41
1              ATACADO BRINDE & CIA       1973.87
2              ATACADO BRINDE & CIA        444.46
3              ATACADO BRINDE & CIA        397.90
4              ATACADO BRINDE & CIA       1304.07
...                             ...           ...
43117  DISTRIBUIDORA ATLETA BEBIDAS       1228.52
43118  DISTRIBUIDORA ATLETA BEBIDAS       1480.32
43119  DISTRIBUIDORA ATLETA BEBIDAS       1553.94
43120  DISTRIBUIDORA ATLETA BEBIDAS       1845.10
43121  DISTRIBUIDORA ATLETA BEBIDAS         88.88

[43122 rows x 2 columns]

# 5. Seleção com iloc

O **iloc** seleciona dados pela **posição numérica**.

### Selecionando linhas e colunas por posição

In [7]:
base_vendas.iloc[0:5, 0:4]

  DATAEMISSAO  CODIGOCLIENTE      DESCRICAOCLIENTE  CODIGOGRUPOPRODUTO
0  2026-02-01       10000449  ATACADO BRINDE & CIA            90013006
1  2026-02-01       10000449  ATACADO BRINDE & CIA            90013011
2  2026-02-01       10000449  ATACADO BRINDE & CIA            90013014
3  2026-02-01       10000449  ATACADO BRINDE & CIA            90013014
4  2026-02-01       10000449  ATACADO BRINDE & CIA            90013022

### Selecionando apenas algumas colunas por posição

In [8]:
base_vendas.iloc[:, [2, 6, 10]]

,DESCRICAOCLIENTE,NOMEPRODUTO,VALORLIQUIDO
0,ATACADO BRINDE & CIA,Isotônico Uva Vitaminado 500ml,472.41
1,ATACADO BRINDE & CIA,Cerveja Lager Standard 350ml (Lata),1973.87
2,ATACADO BRINDE & CIA,Suco de Laranja Integral 500ml,444.46
3,ATACADO BRINDE & CIA,Néctar de Uva Premium 1L,397.90
4,ATACADO BRINDE & CIA,Lúpulo em Pellet para Brassagem 5kg,1304.07
...,...,...,...
43117,DISTRIBUIDORA ATLETA BEBIDAS,Shot Energético Ultra-Concentrado 60ml,1228.52
43118,DISTRIBUIDORA ATLETA BEBIDAS,Hard Seltzer Limão 310ml,1480.32
43119,DISTRIBUIDORA ATLETA BEBIDAS,Hard Seltzer Amora 310ml,1553.94
43120,DISTRIBUIDORA ATLETA BEBIDAS,Hard Seltzer Tangerina 310ml,1845.10
43121,DISTRIBUIDORA ATLETA BEBIDAS,Hard Seltzer Abacaxi 310ml,88.88

# 6. Filtros booleanos

Filtros booleanos servem para retornar apenas as linhas que atendem a uma condição.

### Filtrando valores maiores que 1000

In [9]:
base_vendas[base_vendas["VALORLIQUIDO"] > 1000]

,DATAEMISSAO,CODIGOCLIENTE,DESCRICAOCLIENTE,CODIGOGRUPOPRODUTO,DESCRICAOGRUPOPRODUTO,CODIGOPRODUTO,NOMEPRODUTO,TIPOFATURAMENTO,DESCRICAOTIPOFATURAMENTO,VOLUME,VALORLIQUIDO
1,2026-02-01,10000449,ATACADO BRINDE & CIA,90013011,Cervejas Lager Tradicionais,10001628,Cerveja Lager Standard 350ml (Lata),1,VENDA,50,1973.87
4,2026-02-01,10000449,ATACADO BRINDE & CIA,90013022,Insumos para Produção de Bebidas,10026538,Lúpulo em Pellet para Brassagem 5kg,1,VENDA,100,1304.07
5,2026-02-01,10000449,ATACADO BRINDE & CIA,90013032,Vinhos Tintos Importados,10001164,Vinho Tinto Cabernet Reservado 750ml,7,VENDA FUTURA,0,1872.27
6,2026-02-01,10000449,ATACADO BRINDE & CIA,90013032,Vinhos Tintos Importados,10001164,Vinho Tinto Cabernet Reservado 750ml,8,ENTREGA DE VENDA FUTURA,25,1018.00
8,2026-02-01,10000449,ATACADO BRINDE & CIA,90013060,Bebidas Prontas para Consumo (RTD),10003698,Gin Tônica Frutas Vermelhas 269ml,1,VENDA,9,1261.78
...,...,...,...,...,...,...,...,...,...,...,...
43116,2026-02-28,10005002,DISTRIBUIDORA ATLETA BEBIDAS,91503404,Bebidas Gasosas Saborizadas,10022639,Soda Limonada Diet 350ml,1,VENDA,12,1059.30
43117,2026-02-28,10005002,DISTRIBUIDORA ATLETA BEBIDAS,91503405,Energéticos de Alta Performance,10023656,Shot Energético Ultra-Concentrado 60ml,1,VENDA,4,1228.52
43118,2026-02-28,10005002,DISTRIBUIDORA ATLETA BEBIDAS,91503409,Bebidas Prontas Geladas,10021534,Hard Seltzer Limão 310ml,1,VENDA,9,1480.32
43119,2026-02-28,10005002,DISTRIBUIDORA ATLETA BEBIDAS,91503409,Bebidas Prontas Geladas,10021535,Hard Seltzer Amora 310ml,1,VENDA,9,1553.94
43120,2026-02-28,10005002,DISTRIBUIDORA ATLETA BEBIDAS,91503409,Bebidas Prontas Geladas,10021536,Hard Seltzer Tangerina 310ml,1,VENDA,10,1845.10

### Filtrando um tipo de faturamento específico

In [11]:
base_vendas[base_vendas["DESCRICAOTIPOFATURAMENTO"] == "VENDA"]

,DATAEMISSAO,CODIGOCLIENTE,DESCRICAOCLIENTE,CODIGOGRUPOPRODUTO,DESCRICAOGRUPOPRODUTO,CODIGOPRODUTO,NOMEPRODUTO,TIPOFATURAMENTO,DESCRICAOTIPOFATURAMENTO,VOLUME,VALORLIQUIDO
0,2026-02-01,10000449,ATACADO BRINDE & CIA,90013006,Bebidas Funcionais Vitaminadas,10022282,Isotônico Uva Vitaminado 500ml,1,VENDA,3,472.41
1,2026-02-01,10000449,ATACADO BRINDE & CIA,90013011,Cervejas Lager Tradicionais,10001628,Cerveja Lager Standard 350ml (Lata),1,VENDA,50,1973.87
2,2026-02-01,10000449,ATACADO BRINDE & CIA,90013014,Sucos Naturais Premium,10008337,Suco de Laranja Integral 500ml,1,VENDA,5,444.46
3,2026-02-01,10000449,ATACADO BRINDE & CIA,90013014,Sucos Naturais Premium,10021324,Néctar de Uva Premium 1L,1,VENDA,1,397.90
4,2026-02-01,10000449,ATACADO BRINDE & CIA,90013022,Insumos para Produção de Bebidas,10026538,Lúpulo em Pellet para Brassagem 5kg,1,VENDA,100,1304.07
...,...,...,...,...,...,...,...,...,...,...,...
43117,2026-02-28,10005002,DISTRIBUIDORA ATLETA BEBIDAS,91503405,Energéticos de Alta Performance,10023656,Shot Energético Ultra-Concentrado 60ml,1,VENDA,4,1228.52
43118,2026-02-28,10005002,DISTRIBUIDORA ATLETA BEBIDAS,91503409,Bebidas Prontas Geladas,10021534,Hard Seltzer Limão 310ml,1,VENDA,9,1480.32
43119,2026-02-28,10005002,DISTRIBUIDORA ATLETA BEBIDAS,91503409,Bebidas Prontas Geladas,10021535,Hard Seltzer Amora 310ml,1,VENDA,9,1553.94
43120,2026-02-28,10005002,DISTRIBUIDORA ATLETA BEBIDAS,91503409,Bebidas Prontas Geladas,10021536,Hard Seltzer Tangerina 310ml,1,VENDA,10,1845.10
43121,2026-02-28,10005002,DISTRIBUIDORA ATLETA BEBIDAS,91503409,Bebidas Prontas Geladas,10021537,Hard Seltzer Abacaxi 310ml,1,VENDA,1,88.88

### Combinando duas condições

In [12]:
base_vendas[(base_vendas["VALORLIQUIDO"] > 1000) & (base_vendas["VOLUME"] > 10)]

,DATAEMISSAO,CODIGOCLIENTE,DESCRICAOCLIENTE,CODIGOGRUPOPRODUTO,DESCRICAOGRUPOPRODUTO,CODIGOPRODUTO,NOMEPRODUTO,TIPOFATURAMENTO,DESCRICAOTIPOFATURAMENTO,VOLUME,VALORLIQUIDO
1,2026-02-01,10000449,ATACADO BRINDE & CIA,90013011,Cervejas Lager Tradicionais,10001628,Cerveja Lager Standard 350ml (Lata),1,VENDA,50,1973.87
4,2026-02-01,10000449,ATACADO BRINDE & CIA,90013022,Insumos para Produção de Bebidas,10026538,Lúpulo em Pellet para Brassagem 5kg,1,VENDA,100,1304.07
6,2026-02-01,10000449,ATACADO BRINDE & CIA,90013032,Vinhos Tintos Importados,10001164,Vinho Tinto Cabernet Reservado 750ml,8,ENTREGA DE VENDA FUTURA,25,1018.00
21,2026-02-01,10000449,ATACADO BRINDE & CIA,90013159,Cervejas Puro Malte,10002818,Cerveja Puro Malte Premium 355ml,1,VENDA,100,4431.88
38,2026-02-01,10000964,LOGÍSTICA ESSENCIAL BEBIDAS,90013011,Cervejas Lager Tradicionais,10001628,Cerveja Lager Standard 350ml (Lata),1,VENDA,225,7971.12
...,...,...,...,...,...,...,...,...,...,...,...
43109,2026-02-28,10005002,DISTRIBUIDORA ATLETA BEBIDAS,90013172,Bebidas Mistas Alcoólicas,10015858,Drink Misto Strawberry 269ml,1,VENDA,15,1490.95
43110,2026-02-28,10005002,DISTRIBUIDORA ATLETA BEBIDAS,90013172,Bebidas Mistas Alcoólicas,10015859,Drink Misto Green Apple 269ml,1,VENDA,15,1852.35
43111,2026-02-28,10005002,DISTRIBUIDORA ATLETA BEBIDAS,90013201,Cervejas Artesanais Premium,10001163,Cerveja Artesanal Alpha Gold 600ml,1,VENDA,75,2845.00
43115,2026-02-28,10005002,DISTRIBUIDORA ATLETA BEBIDAS,91503404,Bebidas Gasosas Saborizadas,10022638,Soda Limonada Classic 350ml,1,VENDA,17,1460.25
43116,2026-02-28,10005002,DISTRIBUIDORA ATLETA BEBIDAS,91503404,Bebidas Gasosas Saborizadas,10022639,Soda Limonada Diet 350ml,1,VENDA,12,1059.30

# 7. Usando query()

O **query()** permite escrever filtros de forma mais próxima de uma expressão textual.

In [13]:
base_vendas.query("VALORLIQUIDO > 1000")

,DATAEMISSAO,CODIGOCLIENTE,DESCRICAOCLIENTE,CODIGOGRUPOPRODUTO,DESCRICAOGRUPOPRODUTO,CODIGOPRODUTO,NOMEPRODUTO,TIPOFATURAMENTO,DESCRICAOTIPOFATURAMENTO,VOLUME,VALORLIQUIDO
1,2026-02-01,10000449,ATACADO BRINDE & CIA,90013011,Cervejas Lager Tradicionais,10001628,Cerveja Lager Standard 350ml (Lata),1,VENDA,50,1973.87
4,2026-02-01,10000449,ATACADO BRINDE & CIA,90013022,Insumos para Produção de Bebidas,10026538,Lúpulo em Pellet para Brassagem 5kg,1,VENDA,100,1304.07
5,2026-02-01,10000449,ATACADO BRINDE & CIA,90013032,Vinhos Tintos Importados,10001164,Vinho Tinto Cabernet Reservado 750ml,7,VENDA FUTURA,0,1872.27
6,2026-02-01,10000449,ATACADO BRINDE & CIA,90013032,Vinhos Tintos Importados,10001164,Vinho Tinto Cabernet Reservado 750ml,8,ENTREGA DE VENDA FUTURA,25,1018.00
8,2026-02-01,10000449,ATACADO BRINDE & CIA,90013060,Bebidas Prontas para Consumo (RTD),10003698,Gin Tônica Frutas Vermelhas 269ml,1,VENDA,9,1261.78
...,...,...,...,...,...,...,...,...,...,...,...
43116,2026-02-28,10005002,DISTRIBUIDORA ATLETA BEBIDAS,91503404,Bebidas Gasosas Saborizadas,10022639,Soda Limonada Diet 350ml,1,VENDA,12,1059.30
43117,2026-02-28,10005002,DISTRIBUIDORA ATLETA BEBIDAS,91503405,Energéticos de Alta Performance,10023656,Shot Energético Ultra-Concentrado 60ml,1,VENDA,4,1228.52
43118,2026-02-28,10005002,DISTRIBUIDORA ATLETA BEBIDAS,91503409,Bebidas Prontas Geladas,10021534,Hard Seltzer Limão 310ml,1,VENDA,9,1480.32
43119,2026-02-28,10005002,DISTRIBUIDORA ATLETA BEBIDAS,91503409,Bebidas Prontas Geladas,10021535,Hard Seltzer Amora 310ml,1,VENDA,9,1553.94
43120,2026-02-28,10005002,DISTRIBUIDORA ATLETA BEBIDAS,91503409,Bebidas Prontas Geladas,10021536,Hard Seltzer Tangerina 310ml,1,VENDA,10,1845.10

Também podemos combinar condições.

In [14]:
base_vendas.query("VALORLIQUIDO > 1000 and VOLUME > 10")

,DATAEMISSAO,CODIGOCLIENTE,DESCRICAOCLIENTE,CODIGOGRUPOPRODUTO,DESCRICAOGRUPOPRODUTO,CODIGOPRODUTO,NOMEPRODUTO,TIPOFATURAMENTO,DESCRICAOTIPOFATURAMENTO,VOLUME,VALORLIQUIDO
1,2026-02-01,10000449,ATACADO BRINDE & CIA,90013011,Cervejas Lager Tradicionais,10001628,Cerveja Lager Standard 350ml (Lata),1,VENDA,50,1973.87
4,2026-02-01,10000449,ATACADO BRINDE & CIA,90013022,Insumos para Produção de Bebidas,10026538,Lúpulo em Pellet para Brassagem 5kg,1,VENDA,100,1304.07
6,2026-02-01,10000449,ATACADO BRINDE & CIA,90013032,Vinhos Tintos Importados,10001164,Vinho Tinto Cabernet Reservado 750ml,8,ENTREGA DE VENDA FUTURA,25,1018.00
21,2026-02-01,10000449,ATACADO BRINDE & CIA,90013159,Cervejas Puro Malte,10002818,Cerveja Puro Malte Premium 355ml,1,VENDA,100,4431.88
38,2026-02-01,10000964,LOGÍSTICA ESSENCIAL BEBIDAS,90013011,Cervejas Lager Tradicionais,10001628,Cerveja Lager Standard 350ml (Lata),1,VENDA,225,7971.12
...,...,...,...,...,...,...,...,...,...,...,...
43109,2026-02-28,10005002,DISTRIBUIDORA ATLETA BEBIDAS,90013172,Bebidas Mistas Alcoólicas,10015858,Drink Misto Strawberry 269ml,1,VENDA,15,1490.95
43110,2026-02-28,10005002,DISTRIBUIDORA ATLETA BEBIDAS,90013172,Bebidas Mistas Alcoólicas,10015859,Drink Misto Green Apple 269ml,1,VENDA,15,1852.35
43111,2026-02-28,10005002,DISTRIBUIDORA ATLETA BEBIDAS,90013201,Cervejas Artesanais Premium,10001163,Cerveja Artesanal Alpha Gold 600ml,1,VENDA,75,2845.00
43115,2026-02-28,10005002,DISTRIBUIDORA ATLETA BEBIDAS,91503404,Bebidas Gasosas Saborizadas,10022638,Soda Limonada Classic 350ml,1,VENDA,17,1460.25
43116,2026-02-28,10005002,DISTRIBUIDORA ATLETA BEBIDAS,91503404,Bebidas Gasosas Saborizadas,10022639,Soda Limonada Diet 350ml,1,VENDA,12,1059.30

# 8. Usando unique()

O **unique()** mostra os valores únicos de uma coluna.

In [15]:
base_vendas["TIPOFATURAMENTO"].unique()

array([  1,   7,   8,   3,   2,  14,  13,   5,   6, 100,  82])

# 9. Usando value_counts()

O **value_counts()** conta quantas vezes cada valor aparece.

In [17]:
base_vendas["TIPOFATURAMENTO"].value_counts()

TIPOFATURAMENTO
1      36476
3       2552
8       1630
13       911
2        671
7        578
5        137
100       62
6         60
82        34
14        11
Name: count, dtype: int64

Também podemos usar em outras colunas categóricas.

In [18]:
base_vendas["DESCRICAOGRUPOPRODUTO"].value_counts()

DESCRICAOGRUPOPRODUTO
Bebidas Mistas Alcoólicas                10523
Bebidas Prontas para Consumo (RTD)        3888
Bebidas Energéticas Funcionais            3053
Bebidas Gasosas Saborizadas               2798
Bebidas Energéticas Premium               2522
Sucos Naturais Premium                    2351
Bebidas Prontas Geladas                   2019
Bebidas Funcionais Vitaminadas            1716
Vinhos Tintos Importados                  1539
Cervejas Artesanais Lupuladas             1501
Refrigerantes Sabor Cola                  1371
Cervejas Puro Malte                       1289
Cervejas Especiais de Trigo               1076
Cervejas Artesanais Premium                925
Insumos para Produção de Bebidas           825
Cervejas Lager Tradicionais                821
Destilados Premium                         753
Cervejas Regionais                         732
Refrigerantes Sabor Frutas                 452
Energéticos de Alta Performance            417
Equipamentos para Produção de Bebidas      382
Destilados Especiais                       374
Destilados Clássicos                       359
Bebidas Ice e Cooler                       328
Produção de Bebidas em Grande Escala       255
Destilados Envelhecidos                    218
Controle de Qualidade de Bebidas           191
Refrigerantes Tradicionais                 144
Categoria de Bebidas Diversas              108
Vinhos e Espumantes                         29
Cervejas Comerciais                         19
Produção de Bebidas em Escala               19
Cervejas Industriais                        16
Cervejas de Grande Produção                 15
Bebidas Relaxantes e Digestivas             13
Bebidas Nutricionais                        12
Cervejas Especiais de Produção              11
Cervejas Industriais Premium                10
Destilados de Alta Graduação                10
Base para Bebidas Alcoólicas                 9
Laboratório de Qualidade de Bebidas          8
Bebidas Funcionais Naturais                  7
Matéria-prima para Bebidas                   5
Espumantes e Vinhos Finos                    3
Licores e Destilados Aromáticos              2
Refrigerantes Premium                        2
Destilados Ultra Premium                     1
Cervejas Premium de Mercado                  1
Name: count, dtype: int64

# 10. Usando sort_values()

O **sort_values()** ordena os dados por uma ou mais colunas.

### Ordenando do menor para o maior valor líquido

In [19]:
base_vendas.sort_values("VALORLIQUIDO")

,DATAEMISSAO,CODIGOCLIENTE,DESCRICAOCLIENTE,CODIGOGRUPOPRODUTO,DESCRICAOGRUPOPRODUTO,CODIGOPRODUTO,NOMEPRODUTO,TIPOFATURAMENTO,DESCRICAOTIPOFATURAMENTO,VOLUME,VALORLIQUIDO
7339,2026-02-06,10004228,SUPRIMENTOS BRINDE UNIDO,90013172,Bebidas Mistas Alcoólicas,10015850,Drink Misto Melancia 269ml,2,DEVOLUÇÃO DE VENDA,-150,-18515.25
41042,2026-02-28,10000449,ATACADO BRINDE & CIA,90013018,Destilados Premium,10002994,Vodka Destilada Premium 1L,2,DEVOLUÇÃO DE VENDA,-10,-17540.30
7343,2026-02-06,10004228,SUPRIMENTOS BRINDE UNIDO,90013172,Bebidas Mistas Alcoólicas,10015852,Drink Misto Senses 269ml,2,DEVOLUÇÃO DE VENDA,-90,-16134.30
11429,2026-02-08,10004232,COMERCIAL ALPHA BEBIDAS,90013060,Bebidas Prontas para Consumo (RTD),10003635,Gin Tônica em Lata 269ml,2,DEVOLUÇÃO DE VENDA,-120,-14479.20
7341,2026-02-06,10004228,SUPRIMENTOS BRINDE UNIDO,90013172,Bebidas Mistas Alcoólicas,10015851,Drink Misto Maracujá 269ml,2,DEVOLUÇÃO DE VENDA,-100,-14475.50
...,...,...,...,...,...,...,...,...,...,...,...
31166,2026-02-21,10004227,LOGÍSTICA INTEGRAL DE BEBIDAS,90013059,Bebidas Ice e Cooler,10016993,Cooler de Vinho Rosé 750ml,13,COMPRA,0,342925.00
25772,2026-02-17,10004209,DISTRIBUIDORA VIDA DE BEBIDA,90013159,Cervejas Puro Malte,10002818,Cerveja Puro Malte Premium 355ml,13,COMPRA,0,374496.25
20939,2026-02-15,10000964,LOGÍSTICA ESSENCIAL BEBIDAS,90013032,Vinhos Tintos Importados,10001164,Vinho Tinto Cabernet Reservado 750ml,13,COMPRA,0,396765.27
21005,2026-02-15,10000964,LOGÍSTICA ESSENCIAL BEBIDAS,90013201,Cervejas Artesanais Premium,10001163,Cerveja Artesanal Alpha Gold 600ml,13,COMPRA,0,554255.36
20988,2026-02-15,10000964,LOGÍSTICA ESSENCIAL BEBIDAS,90013159,Cervejas Puro Malte,10002818,Cerveja Puro Malte Premium 355ml,13,COMPRA,0,1122164.40

### Ordenando do maior para o menor valor líquido

In [20]:
base_vendas.sort_values("VALORLIQUIDO", ascending=False)

,DATAEMISSAO,CODIGOCLIENTE,DESCRICAOCLIENTE,CODIGOGRUPOPRODUTO,DESCRICAOGRUPOPRODUTO,CODIGOPRODUTO,NOMEPRODUTO,TIPOFATURAMENTO,DESCRICAOTIPOFATURAMENTO,VOLUME,VALORLIQUIDO
20988,2026-02-15,10000964,LOGÍSTICA ESSENCIAL BEBIDAS,90013159,Cervejas Puro Malte,10002818,Cerveja Puro Malte Premium 355ml,13,COMPRA,0,1122164.40
21005,2026-02-15,10000964,LOGÍSTICA ESSENCIAL BEBIDAS,90013201,Cervejas Artesanais Premium,10001163,Cerveja Artesanal Alpha Gold 600ml,13,COMPRA,0,554255.36
20939,2026-02-15,10000964,LOGÍSTICA ESSENCIAL BEBIDAS,90013032,Vinhos Tintos Importados,10001164,Vinho Tinto Cabernet Reservado 750ml,13,COMPRA,0,396765.27
25772,2026-02-17,10004209,DISTRIBUIDORA VIDA DE BEBIDA,90013159,Cervejas Puro Malte,10002818,Cerveja Puro Malte Premium 355ml,13,COMPRA,0,374496.25
31166,2026-02-21,10004227,LOGÍSTICA INTEGRAL DE BEBIDAS,90013059,Bebidas Ice e Cooler,10016993,Cooler de Vinho Rosé 750ml,13,COMPRA,0,342925.00
...,...,...,...,...,...,...,...,...,...,...,...
7341,2026-02-06,10004228,SUPRIMENTOS BRINDE UNIDO,90013172,Bebidas Mistas Alcoólicas,10015851,Drink Misto Maracujá 269ml,2,DEVOLUÇÃO DE VENDA,-100,-14475.50
11429,2026-02-08,10004232,COMERCIAL ALPHA BEBIDAS,90013060,Bebidas Prontas para Consumo (RTD),10003635,Gin Tônica em Lata 269ml,2,DEVOLUÇÃO DE VENDA,-120,-14479.20
7343,2026-02-06,10004228,SUPRIMENTOS BRINDE UNIDO,90013172,Bebidas Mistas Alcoólicas,10015852,Drink Misto Senses 269ml,2,DEVOLUÇÃO DE VENDA,-90,-16134.30
41042,2026-02-28,10000449,ATACADO BRINDE & CIA,90013018,Destilados Premium,10002994,Vodka Destilada Premium 1L,2,DEVOLUÇÃO DE VENDA,-10,-17540.30
7339,2026-02-06,10004228,SUPRIMENTOS BRINDE UNIDO,90013172,Bebidas Mistas Alcoólicas,10015850,Drink Misto Melancia 269ml,2,DEVOLUÇÃO DE VENDA,-150,-18515.25

### Ordenando por mais de uma coluna

In [21]:
base_vendas.sort_values(["TIPOFATURAMENTO", "VALORLIQUIDO"], ascending=[True, False])

,DATAEMISSAO,CODIGOCLIENTE,DESCRICAOCLIENTE,CODIGOGRUPOPRODUTO,DESCRICAOGRUPOPRODUTO,CODIGOPRODUTO,NOMEPRODUTO,TIPOFATURAMENTO,DESCRICAOTIPOFATURAMENTO,VOLUME,VALORLIQUIDO
5301,2026-02-05,10000449,ATACADO BRINDE & CIA,90013006,Bebidas Funcionais Vitaminadas,10022283,Isotônico Tangerina Vitaminado 500ml,1,VENDA,1000,233305.80
42684,2026-02-28,10004231,DISTRIBUIDORA REINO DAS BEBIDAS,90013006,Bebidas Funcionais Vitaminadas,10022282,Isotônico Uva Vitaminado 500ml,1,VENDA,1002,216757.21
25154,2026-02-17,10004001,LOGÍSTICA GARRAFAS & LOG,90013172,Bebidas Mistas Alcoólicas,10015852,Drink Misto Senses 269ml,1,VENDA,1131,185044.69
12979,2026-02-09,10004221,DISTRIBUIDORA BRINDE & AMIGOS,90013172,Bebidas Mistas Alcoólicas,10015852,Drink Misto Senses 269ml,1,VENDA,1120,181242.46
40243,2026-02-27,10004221,DISTRIBUIDORA BRINDE & AMIGOS,90013172,Bebidas Mistas Alcoólicas,10015851,Drink Misto Maracujá 269ml,1,VENDA,1297,177711.83
...,...,...,...,...,...,...,...,...,...,...,...
1944,2026-02-02,10004007,LOGÍSTICA GUARDA BEBIDAS,91503404,Bebidas Gasosas Saborizadas,10022637,Água Tônica com Limão 350ml,100,OUTRO,0,92.10
39496,2026-02-27,10004004,CENTRAL DE NUTRIÇÃO E BEBIDAS,90013172,Bebidas Mistas Alcoólicas,10015856,Drink Misto Lemonade 269ml,100,OUTRO,0,83.70
39493,2026-02-27,10004004,CENTRAL DE NUTRIÇÃO E BEBIDAS,90013172,Bebidas Mistas Alcoólicas,10015855,Drink Misto Pineapple 269ml,100,OUTRO,0,79.63
39491,2026-02-27,10004004,CENTRAL DE NUTRIÇÃO E BEBIDAS,90013172,Bebidas Mistas Alcoólicas,10015854,Pack Econômico Drink Misto 269ml,100,OUTRO,0,71.62
2268,2026-02-02,10004209,DISTRIBUIDORA VIDA DE BEBIDA,90013172,Bebidas Mistas Alcoólicas,10015855,Drink Misto Pineapple 269ml,100,OUTRO,0,65.69