# Aula 1 – Introdução ao Pandas

## Objetivo da aula

Nesta aula vamos aprender o básico da biblioteca **Pandas**, usada para trabalhar com dados em Python.

Você irá aprender:

- Importar o Pandas
- Ler uma base de dados
- Visualizar os dados
- Entender **Series** e **DataFrame**
- Analisar estrutura e tipos das colunas

# 1. Importando o Pandas

O **Pandas** é a biblioteca mais utilizada para manipulação de dados em Python.

Ela é normalmente importada com o apelido **pd**.

In [1]:
import pandas as pd

# 2. Lendo um arquivo de dados

Vamos carregar uma base utilizando o Pandas.

In [2]:
arquivo = r"C:\Users\Joao.Maria\Documents\curso-python_joao_pedro\Base\Base_analitica_vendas.xlsx"

base_vendas = pd.read_excel(arquivo, sheet_name="Base")

Agora a variável **base_vendas** contém toda a tabela carregada.

# 3. Visualizando os dados

Existem algumas formas simples de visualizar um DataFrame.

### Primeiras linhas da base

In [3]:
base_vendas.head(5)

,DATAEMISSAO,CODIGOCLIENTE,DESCRICAOCLIENTE,CODIGOGRUPOPRODUTO,DESCRICAOGRUPOPRODUTO,CODIGOPRODUTO,NOMEPRODUTO,TIPOFATURAMENTO,DESCRICAOTIPOFATURAMENTO,VOLUME,VALORLIQUIDO
0,2026-02-01,10000449,ATACADO BRINDE & CIA,90013006,Bebidas Funcionais Vitaminadas,10022282,Isotônico Uva Vitaminado 500ml,1,VENDA,3,472.41
1,2026-02-01,10000449,ATACADO BRINDE & CIA,90013011,Cervejas Lager Tradicionais,10001628,Cerveja Lager Standard 350ml (Lata),1,VENDA,50,1973.87
2,2026-02-01,10000449,ATACADO BRINDE & CIA,90013014,Sucos Naturais Premium,10008337,Suco de Laranja Integral 500ml,1,VENDA,5,444.46
3,2026-02-01,10000449,ATACADO BRINDE & CIA,90013014,Sucos Naturais Premium,10021324,Néctar de Uva Premium 1L,1,VENDA,1,397.90
4,2026-02-01,10000449,ATACADO BRINDE & CIA,90013022,Insumos para Produção de Bebidas,10026538,Lúpulo em Pellet para Brassagem 5kg,1,VENDA,100,1304.07

### Mostrar a tabela completa

In [4]:
display(base_vendas)

,DATAEMISSAO,CODIGOCLIENTE,DESCRICAOCLIENTE,CODIGOGRUPOPRODUTO,DESCRICAOGRUPOPRODUTO,CODIGOPRODUTO,NOMEPRODUTO,TIPOFATURAMENTO,DESCRICAOTIPOFATURAMENTO,VOLUME,VALORLIQUIDO
0,2026-02-01,10000449,ATACADO BRINDE & CIA,90013006,Bebidas Funcionais Vitaminadas,10022282,Isotônico Uva Vitaminado 500ml,1,VENDA,3,472.41
1,2026-02-01,10000449,ATACADO BRINDE & CIA,90013011,Cervejas Lager Tradicionais,10001628,Cerveja Lager Standard 350ml (Lata),1,VENDA,50,1973.87
2,2026-02-01,10000449,ATACADO BRINDE & CIA,90013014,Sucos Naturais Premium,10008337,Suco de Laranja Integral 500ml,1,VENDA,5,444.46
3,2026-02-01,10000449,ATACADO BRINDE & CIA,90013014,Sucos Naturais Premium,10021324,Néctar de Uva Premium 1L,1,VENDA,1,397.90
4,2026-02-01,10000449,ATACADO BRINDE & CIA,90013022,Insumos para Produção de Bebidas,10026538,Lúpulo em Pellet para Brassagem 5kg,1,VENDA,100,1304.07
...,...,...,...,...,...,...,...,...,...,...,...
43117,2026-02-28,10005002,DISTRIBUIDORA ATLETA BEBIDAS,91503405,Energéticos de Alta Performance,10023656,Shot Energético Ultra-Concentrado 60ml,1,VENDA,4,1228.52
43118,2026-02-28,10005002,DISTRIBUIDORA ATLETA BEBIDAS,91503409,Bebidas Prontas Geladas,10021534,Hard Seltzer Limão 310ml,1,VENDA,9,1480.32
43119,2026-02-28,10005002,DISTRIBUIDORA ATLETA BEBIDAS,91503409,Bebidas Prontas Geladas,10021535,Hard Seltzer Amora 310ml,1,VENDA,9,1553.94
43120,2026-02-28,10005002,DISTRIBUIDORA ATLETA BEBIDAS,91503409,Bebidas Prontas Geladas,10021536,Hard Seltzer Tangerina 310ml,1,VENDA,10,1845.10
43121,2026-02-28,10005002,DISTRIBUIDORA ATLETA BEBIDAS,91503409,Bebidas Prontas Geladas,10021537,Hard Seltzer Abacaxi 310ml,1,VENDA,1,88.88

### Exibir diretamente a variável

In [5]:
base_vendas

,DATAEMISSAO,CODIGOCLIENTE,DESCRICAOCLIENTE,CODIGOGRUPOPRODUTO,DESCRICAOGRUPOPRODUTO,CODIGOPRODUTO,NOMEPRODUTO,TIPOFATURAMENTO,DESCRICAOTIPOFATURAMENTO,VOLUME,VALORLIQUIDO
0,2026-02-01,10000449,ATACADO BRINDE & CIA,90013006,Bebidas Funcionais Vitaminadas,10022282,Isotônico Uva Vitaminado 500ml,1,VENDA,3,472.41
1,2026-02-01,10000449,ATACADO BRINDE & CIA,90013011,Cervejas Lager Tradicionais,10001628,Cerveja Lager Standard 350ml (Lata),1,VENDA,50,1973.87
2,2026-02-01,10000449,ATACADO BRINDE & CIA,90013014,Sucos Naturais Premium,10008337,Suco de Laranja Integral 500ml,1,VENDA,5,444.46
3,2026-02-01,10000449,ATACADO BRINDE & CIA,90013014,Sucos Naturais Premium,10021324,Néctar de Uva Premium 1L,1,VENDA,1,397.90
4,2026-02-01,10000449,ATACADO BRINDE & CIA,90013022,Insumos para Produção de Bebidas,10026538,Lúpulo em Pellet para Brassagem 5kg,1,VENDA,100,1304.07
...,...,...,...,...,...,...,...,...,...,...,...
43117,2026-02-28,10005002,DISTRIBUIDORA ATLETA BEBIDAS,91503405,Energéticos de Alta Performance,10023656,Shot Energético Ultra-Concentrado 60ml,1,VENDA,4,1228.52
43118,2026-02-28,10005002,DISTRIBUIDORA ATLETA BEBIDAS,91503409,Bebidas Prontas Geladas,10021534,Hard Seltzer Limão 310ml,1,VENDA,9,1480.32
43119,2026-02-28,10005002,DISTRIBUIDORA ATLETA BEBIDAS,91503409,Bebidas Prontas Geladas,10021535,Hard Seltzer Amora 310ml,1,VENDA,9,1553.94
43120,2026-02-28,10005002,DISTRIBUIDORA ATLETA BEBIDAS,91503409,Bebidas Prontas Geladas,10021536,Hard Seltzer Tangerina 310ml,1,VENDA,10,1845.10
43121,2026-02-28,10005002,DISTRIBUIDORA ATLETA BEBIDAS,91503409,Bebidas Prontas Geladas,10021537,Hard Seltzer Abacaxi 310ml,1,VENDA,1,88.88

# 4. Estrutura do Pandas

O Pandas possui duas estruturas principais:

| Estrutura | Descrição |
|---|---|
| **Series** | Uma única coluna |
| **DataFrame** | Uma tabela com várias colunas |

## 4.1 Series (uma coluna)

Uma **Series** representa apenas uma coluna da base.

In [6]:
serie_clientes = base_vendas["DESCRICAOCLIENTE"]

serie_clientes

0                ATACADO BRINDE & CIA
1                ATACADO BRINDE & CIA
2                ATACADO BRINDE & CIA
3                ATACADO BRINDE & CIA
4                ATACADO BRINDE & CIA
                     ...
43117    DISTRIBUIDORA ATLETA BEBIDAS
43118    DISTRIBUIDORA ATLETA BEBIDAS
43119    DISTRIBUIDORA ATLETA BEBIDAS
43120    DISTRIBUIDORA ATLETA BEBIDAS
43121    DISTRIBUIDORA ATLETA BEBIDAS
Name: DESCRICAOCLIENTE, Length: 43122, dtype: str

Verificando o tipo da estrutura:

In [7]:
type(serie_clientes)

pandas.Series

## 4.2 DataFrame (tabela)

Um **DataFrame** representa uma tabela completa.

In [8]:
type(base_vendas)

pandas.DataFrame

Também podemos criar um DataFrame selecionando colunas específicas.

In [9]:
dataframe_clientes = base_vendas[["DESCRICAOCLIENTE"]]

dataframe_clientes

                   DESCRICAOCLIENTE
0              ATACADO BRINDE & CIA
1              ATACADO BRINDE & CIA
2              ATACADO BRINDE & CIA
3              ATACADO BRINDE & CIA
4              ATACADO BRINDE & CIA
...                             ...
43117  DISTRIBUIDORA ATLETA BEBIDAS
43118  DISTRIBUIDORA ATLETA BEBIDAS
43119  DISTRIBUIDORA ATLETA BEBIDAS
43120  DISTRIBUIDORA ATLETA BEBIDAS
43121  DISTRIBUIDORA ATLETA BEBIDAS

[43122 rows x 1 columns]

Verificando o tipo:

In [10]:
type(dataframe_clientes)

pandas.DataFrame

# 5. Estrutura da base de dados

Podemos analisar a estrutura da base com algumas propriedades importantes.

### Colunas da base

In [11]:
base_vendas.columns

Index(['DATAEMISSAO', 'CODIGOCLIENTE', 'DESCRICAOCLIENTE',
       'CODIGOGRUPOPRODUTO', 'DESCRICAOGRUPOPRODUTO', 'CODIGOPRODUTO',
       'NOMEPRODUTO', 'TIPOFATURAMENTO', 'DESCRICAOTIPOFATURAMENTO', 'VOLUME',
       'VALORLIQUIDO'],
      dtype='str')

Também é possível converter para lista:

In [12]:
list(base_vendas.columns)

['DATAEMISSAO',
 'CODIGOCLIENTE',
 'DESCRICAOCLIENTE',
 'CODIGOGRUPOPRODUTO',
 'DESCRICAOGRUPOPRODUTO',
 'CODIGOPRODUTO',
 'NOMEPRODUTO',
 'TIPOFATURAMENTO',
 'DESCRICAOTIPOFATURAMENTO',
 'VOLUME',
 'VALORLIQUIDO']

### Tamanho da base

Mostra **linhas e colunas**.

In [13]:
base_vendas.shape

(43122, 11)

# 6. Tipos de dados

O Pandas interpreta automaticamente o tipo de cada coluna.

In [14]:
base_vendas.dtypes

DATAEMISSAO                 datetime64[us]
CODIGOCLIENTE                        int64
DESCRICAOCLIENTE                       str
CODIGOGRUPOPRODUTO                   int64
DESCRICAOGRUPOPRODUTO                  str
CODIGOPRODUTO                        int64
NOMEPRODUTO                            str
TIPOFATURAMENTO                      int64
DESCRICAOTIPOFATURAMENTO               str
VOLUME                               int64
VALORLIQUIDO                       float64
dtype: object

# 7. Informações gerais da base

A função **info()** mostra:

- nome das colunas
- tipo de dados
- quantidade de valores nulos

In [15]:
base_vendas.info()

<class 'pandas.DataFrame'>
RangeIndex: 43122 entries, 0 to 43121
Data columns (total 11 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   DATAEMISSAO               43122 non-null  datetime64[us]
 1   CODIGOCLIENTE             43122 non-null  int64
 2   DESCRICAOCLIENTE          43122 non-null  str
 3   CODIGOGRUPOPRODUTO        43122 non-null  int64
 4   DESCRICAOGRUPOPRODUTO     43122 non-null  str
 5   CODIGOPRODUTO             43122 non-null  int64
 6   NOMEPRODUTO               43122 non-null  str
 7   TIPOFATURAMENTO           43122 non-null  int64
 8   DESCRICAOTIPOFATURAMENTO  43122 non-null  str
 9   VOLUME                    43122 non-null  int64
 10  VALORLIQUIDO              43122 non-null  float64
dtypes: datetime64[us](1), float64(1), int64(5), str(4)
memory usage: 3.6 MB